# Generated by Django 3.0.3 on 2020-02-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHindi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThreatName', models.CharField(max_length=255, null=True)),
                ('WhatItIs', models.TextField(null=True)),
                ('WhyItOccurs', models.TextField(null=True)),
                ('HowToIdentify', models.TextField(null=True)),
                ('Others', models.TextField(null=True)),
                ('WhenItOccurs', models.TextField(null=True)),
                ('ImagePath', models.ImageField(null=True, upload_to='image')),
                ('ProductName', models.CharField(max_length=250, null=True)),
                ('BrandLogoImgPath', models.ImageField(null=True, upload_to='image')),
                ('ProductImgPath', models.ImageField(null=True, upload_to='image')),
                ('BrandCommunicationImgPath', models.ImageField(null=True, upload_to='image')),
                ('BrandCommunicationVedioURL', models.FileField(null=True, upload_to='image')),
                ('Dosage', models.CharField(max_length=50, null=True)),
                ('WhenToApply', models.ImageField(null=True, upload_to='image')),
                ('WhenToApplyText', models.TextField(null=True)),
                ('MethodOfApplication', models.TextField(null=True)),
                ('ActiveIngredients', models.TextField(null=True)),
                ('AlsoApplicableCrop', models.TextField(null=True)),
            ],
        ),
    ]
